#!/bin/bash

echo "--- downloading FFMPEG into .bin/ ---"
mkdir -p .bin
cd .bin || exit
curl -C - -O https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
echo "--- unpacking FFMPEG ---"
tar xv --strip-components=1 -f ffmpeg-git-amd64-static.tar.xz
cd ..
echo "--- installing ffmpeg-normalize into .bin/venv/bin ---"
python3 -m venv .bin/venv
.bin/venv/bin/pip install ffmpeg-normalize
